package it.water.email.api;

import it.water.core.api.service.BaseEntitySystemApi;
import it.water.email.model.EMailTemplate;

/**
 * @Generated by Water Generator
 * This interface defines the internally exposed methods for the entity and allows interaction with it bypassing permission system.
 * The main goals of EMailSystemApi is to validate the entity and pass it to the persistence layer.
 */
public interface EMailTemplateSystemApi extends BaseEntitySystemApi<EMailTemplate> {

}