package it.water.email.api;

import it.water.core.api.repository.BaseRepository;
import it.water.email.model.EMailTemplate;

/**
 * @Generated by Water Generator
 * Interface component for EMail Repository.
 * It is used for CRUD operations, and to interact with the persistence layer.
 */
public interface EMailTemplateRepository extends BaseRepository<EMailTemplate> {
    /**
     * Return EMail template from its name
     * @param name
     * @return
     */
    EMailTemplate findByName(String name);
}
