package it.water.email.repository;

import it.water.core.api.repository.query.Query;
import it.water.core.api.repository.query.QueryBuilder;
import it.water.core.interceptors.annotations.FrameworkComponent;
import it.water.email.api.EMailTemplateRepository;
import it.water.email.model.EMailTemplate;
import it.water.repository.jpa.WaterJpaRepositoryImpl;

/**
 * @Generated by Water Generator
 * Repository Class for EMailTemplate entity.
 */
@FrameworkComponent
public class EMailRepositoryImpl extends WaterJpaRepositoryImpl<EMailTemplate> implements EMailTemplateRepository {
    private static final String EMAIL_PERSISTENCE_UNIT = "emailTemplate-persistence-unit";

    public EMailRepositoryImpl() {
        super(EMailTemplate.class, EMAIL_PERSISTENCE_UNIT);
    }

    @Override
    public EMailTemplate findByName(String name) {
        QueryBuilder qb = this.getQueryBuilderInstance();
        Query q = qb.field("templateName").equalTo(name);
        return this.find(q);
    }
}
